name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      # See action.yml for all options
      - uses: ShaunMWallace/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Languages Section
          plugin_languages: yes
          plugin_languages_details: percentage # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%
          plugin_languages_indepth: no # Get indepth stats (see documentation before enabling)
          plugin_languages_analysis_timeout: 15
          plugin_languages_recent_load: 500
          commits_authoring: shaunw21@gmail.com, shaun.wallace@weather.com

